go install github.com/formal/spig/aeskey
go install github.com/formal/spig/echo
go install github.com/formal/spig/echoworker
go install github.com/formal/spig/encrypt0
go install github.com/formal/spig/encrypt0worker
go install github.com/formal/spig/encrypt1
go install github.com/formal/spig/encrypt1worker
go install github.com/formal/spig/nested
go install github.com/formal/spig/nestedworker
go install github.com/formal/spig/nsska
go install github.com/formal/spig/nssktokens
go install github.com/formal/spig/nsskworkers
go install github.com/formal/spig/ora
go install github.com/formal/spig/ortokens
go install github.com/formal/spig/orworkers
go install github.com/formal/spig/server
go install github.com/formal/spig/shownssk
go install github.com/formal/spig/showor
go install github.com/formal/spig/showzk
go install github.com/formal/spig/utils
go install github.com/formal/spig/workers
go install github.com/formal/spig/zk
go install github.com/formal/spig/zknumbers
go install github.com/formal/spig/zkworker
